#!/bin/bash
COUNT=$#
test $COUNT -lt 1 && {
    echo "Usage: $0 <markdown files>"
    exit 1
}
MKD=`which multimarkdown`
test -z $MKD && {
    MKD=`which markdown`
}
test -z $MKD && {
    echo "ERROR: Please install 'markdown' or 'multimarkdown'"
    exit 1
}

htmlize() {
FILE=$1
HTMLFILE=`echo $FILE | sed -e's:\..*:.html:g'`
IS_OK=`echo $HTMLFILE | grep html | wc -l`
test $IS_OK -eq 0 && {
    echo "ERROR: $FILE is not an acceptable filename. Needs an extension."
    exit 1
}
echo "Using $MKD on $FILE to create $HTMLFILE"
cat > $HTMLFILE << HEADER
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <title>VIC by Selective Intellect</title>
    <link rel="stylesheet" href="stylesheets/styles.css">
    <link rel="stylesheet" href="stylesheets/pygment_trac.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="javascripts/respond.js"></script>
    <!--[if lt IE 9]>
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!--[if lt IE 8]>
    <link rel="stylesheet" href="stylesheets/ie.css">
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

  </head>
  <body>
      <div id="header">
        <nav>
          <li class="fork"><a href="https://github.com/vikasnkumar/vic">View On GitHub</a></li>
          <li class="downloads"><a href="https://github.com/vikasnkumar/vic/zipball/master">ZIP</a></li>
          <li class="downloads"><a href="https://github.com/vikasnkumar/vic/tarball/master">TAR</a></li>
          <li class="title">DOWNLOAD SOURCE</li>
        </nav>
      </div><!-- end header -->

    <div class="wrapper">
    <section>
        <div id="title">
        <p>VIC&trade; - A compiler for Microchip&#8217;s PIC&reg; Microcontrollers</p>
        <hr>
        <span class="credits left">Project sponsored by <a
        href="http://selectiveintellect.com">Selective Intellect</a></span>
        <span class="credits right">Hosted on GitHub Pages &mdash; Theme by <a href="https://twitter.com/michigangraham">mattgraham</a></span>
        <br/><br/>
        <span class="credits left"><a href="./index.html">Table of Contents</a></span>
        <span class="credits right"><a href="__PREV__">Prev</a>&nbsp;&nbsp;<a href="__NEXT__">Next</a></span>
        </div>
HEADER
NEXTLINE=$(grep @@NEXT@@ $FILE | sed -e 's/.*@@NEXT@@ \(.*md\)/\1/g' | awk '{print $1;}')
PREVLINE=$(grep @@PREV@@ $FILE | sed -e 's/.*@@PREV@@ \(.*md\)/\1/g' | awk '{print $1;}')
NEXTLINE=$(echo $NEXTLINE | sed -e 's/\.md$/\.html/g')
PREVLINE=$(echo $PREVLINE | sed -e 's/\.md$/\.html/g')
sed -e "s/.*@@NEXT@@.*//g" $FILE > ${FILE}.1
sed -e "s/.*@@PREV@@.*//g" $FILE > ${FILE}.1
$MKD ${FILE}.1 >> $HTMLFILE
rm -f ${FILE}.1

cat >> $HTMLFILE << FOOTER
    <hr>
    <div id="title">
    <span class="credits left"><a href="./index.html">Table of Contents</a></span>
    <span class="credits right"><a href="__PREV__">Prev</a>&nbsp;&nbsp;<a href="__NEXT__">Next</a></span>
    <br/><br/>
    <p style="font-size:14px;">Vikas N Kumar (<a href="https://github.com/vikasnkumar"
class="user-mention">@vikasnkumar</a>) is the author of <strong>VIC&trade;</strong>. All copyrights belong to the author.</p>
    <p style="font-size:12px;">VIC&trade; is licensed under the <a
    href="http://dev.perl.org/licenses/">license terms of Perl</a>.
    <br/>
    The development of VIC&trade; is sponsored by <a
    href="http://selectiveintellect.com">Selective Intellect.</a>
    </p>
    <p style="font-size:11px;">
        This page was last updated on __FDATE__.
    </p>
    </div>
    </section>
    </div><!-- end wrapper -->
    <!--[if !IE]><script>fixScale(document);</script><![endif]-->
  </body>
FOOTER
    DATE=`git log -1 --pretty="format:%ai" $FILE`
    sed -i -e "s/__FDATE__/${DATE}/g" $HTMLFILE
    sed -i -e "s/__PREV__/${PREVLINE}/g" $HTMLFILE
    sed -i -e "s/__NEXT__/${NEXTLINE}/g" $HTMLFILE
}

for i in $@; do
    htmlize $i
done
